func main() {
	mux := http.NewServeMux()

	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		// Get the token generated by nosurf for THIS specific request
		token := nosurf.Token(r)
		
		fmt.Fprintf(w, `
			<html>
				<head>
					<script src="https://unpkg.com/htmx.org"></script>
					<!-- The Secret Key for HTMX -->
					<meta name="csrf-token" content="%s">
				</head>
				<body hx-headers='{"X-CSRF-Token": "%s"}'>
					<h1>Altradits Secure Terminal</h1>
					<button hx-post="/vault/drain" hx-target="#status">
						Execute Transfer
					</button>
					<div id="status"></div>
				</body>
			</html>
		`, token, token)
	})

	// Wrap the entire router in the CSRF Shield
	http.ListenAndServe(":8080", CSRFHandler(mux))
}